require("bufferline").setup({})
require("hop").setup({ keys = "etovxqpdygfblzhckisuran" })
require("toggleterm").setup({})
require("nvim-web-devicons").setup({})
require("neogit").setup({})
require("nvim_comment").setup({ integrations = { gitffview = true } })
